package queue

func Exec() {
	q := CreateQueueArr[int](10)
	q.PrioQueAsc(2)
	q.EnqueueArr(5)
	q.PrioQueAsc(12)
	q.EnqueueArr(100)
	q.PrioQueDsc(101)
	q.PrioQueDsc(927)
	q.EnqueueArr(45)
	q.PrioQueAsc(10)
	q.EnqueueArr(65)
	q.EnqueueArr(75)
	q.PrioQueAsc(11)
	q.PrioQueAsc(99)
	q.nextQm(35)
	q.EnqueueArr(32)
	q.PollAll()
	q.printQueStat()
	q.PollAll()
	q.printQueStat()
	q.EnqueueArr(25)
	q.EnqueueArr(85)
	q.EnqueueArr(95)
	q.EnqueueArr(15)
	q.EnqueueArr(55)
	q.PollAll()
	q.printQueStat()
	q.nextQm(55)
	q.PollAll()
	q.reverseQArr()
	q.PollAll()
	q.printQueStat()
}
